function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=params(38);
    ys_(5)=params(38);
    ys_(6)=params(38);
    ys_(7)=params(38);
    ys_(3)=params(5);
    ys_(2)=100*((1+params(5)/100)/(1/(1+params(6)/100)*(1+params(38)/100)^(-params(13)))-1);
    ys_(1)=params(4);
    % Auxiliary equations
end
